### ISSUE TITLE
PayPal silently fails when paykey request includes ipv6

### ISSUE THREAD

**Issue by dnich** [paypal/adaptivepayments-sdk-php#57]
This issue has been verified by tech support as a PayPal error, see incident 151114-000075.  I am raising the issue here as well because it is unclear whether the resolution is to update the PayPal server code or the sdk.

Issue: When using the sdk to retrieve a paykey, somewhere inside the sdk code the sellers server ipv6 address is sent along with the request.  However, the PayPal server code can only handle ipv4 addresses.

Symptoms: The PayPal server code generates an error message to a log file.  No error is raised and a valid paykey is returned.  After the buyer logs into their account and clicks 'pay', the system may or may not fail, returning an error message to the buyer "Your payment can't be completed.  Please return to the participating website and try again."   Note that this is an intermittent error.  It seems that other variables effect whether or not the transaction fails, but I have been told that the ip address is the root cause.

Result: The buyer is unable to complete the transaction and either abandons it or clicks return to the store in which case the cancelURL is called.  The seller is not notified that an error has occurred.  PayPal is not notified that an error has occurred (except in the log file as noted above).  The end result is lost sales.

Test case: Working with tech support, I was able to create a failed transaction.  Tech support, using my code was able to generate a successful transaction, and moments later, I was able to generate a failed transaction again.  Details can be found in the incident report.

**Comment by jaypatel512** [comment]
Hey @dnich !

I have made a quick fix to not use IPv6 based addresses, that should solve the issue. Please update your dependencies, by running `composer update` on the project root location. Make sure you have the latest [v3.2.1](https://github.com/paypal/sdk-core-php/releases/tag/v3.2.1) release for `sdk-core-php`. If it does not happen, please remove the composer cache and try again. 

Let me know if this fixes your issue.

**Comment by dnich** [comment]
Jay, 
Thanks for your help and response.  I have updated my sdk to:
paypal/adaptivepayments-sdk-php v3.9.0
paypal/sdk-core-php v3.2.1

Unfortunately, this did not resolve my issue.  As I stated in my bug report, tech support assumed that ip address was the root cause of the problem.  Your update should eliminate this as a possibility and I will have them verify that the log files no longer generate this error message.

I guess this was a red herring, and the real problem lies deeper in the PayPal server.  Hopefully, having this resolved will unmask the real source of the failure.

I will update my incident report with what we have done today and let you know what I hear back from them about it.

Thanks for your help.  Much appreciated.

David

**Comment by jaypatel512** [comment]
Hey @dnich !

Also, please make sure to ask them to confirm if they are no longer seeing the IPv6 in the header.

**Comment by jaypatel512** [comment]
Hey @dnich !

Apparently, the issue was still about sending IPv6. I have made another release, that should fix that issue. Here is the release: [v3.2.2](https://github.com/paypal/sdk-core-php/releases/tag/v3.2.2)

Let me know if updating now fixes the problem.

**Comment by dnich** [comment]
I am not able to get composer to update to this release.  I have tried clearing the cache and I reverted to the previous version and then upgraded again and I still have v3.2.1.  Is there a composer command to force this new version?

**Comment by jaypatel512** [comment]
Can you try again now. I told `composer` to force update our packages. For some reason it didn't update.

**Comment by dnich** [comment]
I have installed v3.2.2 and was able to get a completed transaction.  As I mentioned, this was an intermittent problem, so I will continue to monitor it for a while, but for now it seems to be fixed.  Thank you for your help.
